# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# FIXME: double-check
[tool.setuptools.packages.find]
include = ["woke_notes*"]

[project]
name = "woke-notes"
version = "0.1.0"
requires-python = ">= 3.10"
dependencies = [
	"pykka==4.4.2",
	"ruamel.yaml==0.19.1",
	"paho-mqtt==2.1.0",
	"watchdog==6.0.0",
]
authors = [
  {name = "Michael Seydel", email = "contact@micseydel.me"},
]
description = "wake up"
# FIXME
#readme = "README.md"
license = "MIT"
